<div style="width:300px;">
    <h1 align="center">ASK US A QUESTION:</h1>
    <form method="post" action="<?php echo $this->getUrl('questions/index/save') ?>">
        <div class="input-box" align="center">
        <span>
            <input type="text" id="name" name="name" placeholder="Ivan" class="input-text required-entry"/>
        </span>
        </div>
        <div class="input-box" align="center">
        <span>
            <input type="email" id="email" name="email" placeholder="ivan@example.com" class="input-text required-entry"/>
        </span>
        </div>
        <div class="input-box" align="center">
        <span>
            <textarea name="question" id="question"></textarea>
        </span>
        </div>
        <div class="input-box" align="center">
            <input type="submit" value="ask" class="button"/>
        </div>
    </form>
</div>
