<div style="width:500px;">
    <h1 align="center"><?php echo $this->__('ANSWERED QUESTIONS:') ?></h1>
    <div style="margin-bottom: 55px;">
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <?php foreach ($this->getCollection() as $question): ?>
        <div class="block-title">
            <strong>
                <span><?php echo $this->__('Q: ') ?></span>
            </strong>
            <?php echo $question->getQuestion() ?><br>
            <strong>
                <span><?php echo $this->__('A: ') ?></span>
            </strong>
            <?php echo $question->getAnswer() ?>
        </div>
    <?php endforeach; ?>
</div>